Repository Puzzle-Capstone/puzzlrs-ui, pull requests merged in 2022-02, with the labels that each got.

#14 Feature/user profile
  src/components/App.test.tsx
  src/components/UserProfile.tsx
  src/components/UserProfilePuzzle.tsx
  src/css/App.css
  src/css/Home.css
  src/css/UserProfile.css
  src/css/UserProfilePuzzle.css
Labels: display

#13 Feature/puzzle page
  src/components/App.tsx
  src/components/Hamburger.tsx
  src/components/Nav.tsx
  src/components/Puzzle.tsx
  src/components/PuzzleContainer.tsx
  src/components/PuzzleDetails.tsx
  src/css/App.css
  src/css/Hamburger.css
  src/css/Nav.css
  src/css/Puzzle.css
  src/css/PuzzleContainer.css
Labels: display

#16 Feature/design
  src/components/AddPuzzleForm.tsx
  src/components/PuzzleContainer.tsx
  src/css/PuzzleContainer.css
  src/utils.js
Labels: display, refactor

#18 Feature/display puzzles
  src/components/App.tsx
  src/components/Context.tsx
  src/components/Puzzle.tsx
  src/components/PuzzleContainer.tsx
  src/utils.tsx
Labels: feature

#29 Feature/filter puzzles
  src/components/PuzzleContainer.tsx
  src/utils.tsx
Labels: bug, feature

#34 Feature/request puzzle
  src/Context.tsx
  src/components/AddPuzzleForm.tsx
  src/components/Nav.tsx
  src/components/Puzzle.tsx
  src/components/PuzzleDetails.tsx
  src/components/PuzzleGridModal.tsx
  src/components/RequestDetails.tsx
  src/components/UserProfile.tsx
  src/components/UserProfilePuzzle.tsx
  src/components/UserPuzzleModal.tsx
  src/components/UserReceivedRequestModal.tsx
  src/components/UserSentRequestModal.tsx
  src/css/Puzzle.css
  src/css/PuzzleGridModal.css
  src/css/UserProfilePuzzle.css
  src/css/UserReceivedRequestModal.css
  src/interfaces.tsx
  src/utils.tsx
Labels: feature, refactor

#35 Feature/error handling
  public/index.html
  src/Context.tsx
  src/components/AddPuzzleForm.tsx
  src/components/App.tsx
  src/components/ErrorPage.tsx
  src/components/Hamburger.tsx
  src/components/Home.tsx
  src/components/Nav.tsx
  src/components/Puzzle.tsx
  src/components/PuzzleContainer.tsx
  src/components/PuzzleGridModal.tsx
  src/components/UserProfile.tsx
  src/components/UserProfilePuzzle.tsx
  src/components/UserPuzzleModal.tsx
  src/components/UserReceivedRequestModal.tsx
  src/components/UserSentRequestModal.tsx
  src/css/Home.css
  src/interfaces.tsx
  src/utils.tsx
Labels: feature

#36 Feature/final design
  public/favicon.ico
  public/index.html
  src/components/AddPuzzleForm.tsx
  src/components/Nav.tsx
  src/components/PuzzleContainer.tsx
  src/css/AddPuzzleForm.css
  src/css/App.css
  src/css/Hamburger.css
  src/css/Home.css
  src/css/Nav.css
  src/css/Puzzle.css
  src/css/PuzzleContainer.css
  src/css/UserProfile.css
  src/css/UserProfilePuzzle.css
  src/interfaces.tsx
Labels: display

#37 Feature/modal design
  src/components/PuzzleGridModal.tsx
  src/components/UserPuzzleModal.tsx
  src/components/UserReceivedRequestModal.tsx
  src/components/UserSentRequestModal.tsx
  src/css/Home.css
  src/css/PuzzleGridModal.css
  src/css/UserProfile.css
Labels: display

#40 Feature/filter
  src/components/PuzzleContainer.tsx
  src/css/PuzzleContainer.css
Labels: bug
